# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170919_0938'),
        ('blog', '0007_subscribemodel'),
    ]

    operations = [
    ]
