# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 10:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_merge_20170919_1736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubscribeModel',
        ),
    ]
