# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_slug'),
        ('blog', '0011_delete_subscribemodel'),
    ]

    operations = [
    ]
